### ISSUE TITLE
Establishing a system of bin validation with universally-conserved genes

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#12]
## Tasks

- [ ] lineage-specific marker sets (assessment of frequency distributions)
- [ ] putative bin taxon placement (something equivalent to pplacer?)
- [ ] bin completeness and purity estimates with lineage-specific marker set

## Required Datasets

- Lineage-specific marker sets and co-located groups based on the annotated PFAM and TIGRFAM domains in good-quality genomes in the IMG database
- Include many genes that are found in multiple copies amongst the reference genome set
- Therefore we will assess frequency distributions for all genes

## Expectations and Approach

- [ ] Expand the putative marker set by including all genes that are universally shared amongst each taxon.
- Use both single-copy and multi-copy genes that are universally conserved.
- [ ] Initially place the putative bin in a reference tree to identify the appropriate marker gene set.
- only carry out this calculation if the subset of this core 43 genes found in a bin appear taxonomically congruent.
- [ ] Account for fragmented genes in the assembly.
- Count marker genes according to the length fraction of alignments produced by HMMER.
- Check for taxonomic congruity.
- [ ] Convert gene counts in taxonomically congruous groups to adjusted gene counts.
- If the gene is not present, 0 is recorded
- If the count is a low outlier according to the gene’s distribution in reference genomes, 0 is recorded
- if the count is a high outlier, 2 is recorded
- if the count is not an outlier, 1 is recorded

- [ ] Completeness estimation
- [ ] Purity estimation

## Evaluation Datasets

- [ ] A dataset which contains many genomes closely related to sequenced isolates, and/or uncultured species that have sequenced close free-living relatives (MIX-51 datasets)
- [ ] A dataset containing many novel and divergent organisms, where the closest relative in public databases is quite dissimilar
- search IMG for genomes for which the closest relative shares <80% average nucleotide identity.
- set of 2,500 hand curated metagenome-assembled genomes (MAGs) representing many candidate phyla.
- These genomes will be removed from an offline copy of the NCBI NR and taxonomy databases that our algorithm uses for taxonomic assignment.
- Assign a reasonable taxonomic classification to simulated contigs from these genomes in the absence of an exact or close match.
- Effectively group contigs together that are closely related.
- Use simulated collections of contigs from single and mixed assemblies from these genomes to evaluate completeness and purity estimates.
- [ ] synthetic communities
- [ ] simulated communities
- [ ] real metagenomic datasets
