### ISSUE TITLE
Drivers of diversity in soil

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#14]
## Tasks

- [ ] Implement incorporation of other external annotation tools for post processing of bins.

## Required Datasets:

1. Binned Metagenomes/Pangenomes

## Expectations and Approach:

- [ ] KEGG database annotations [kofamscan](</path/to/kofamscan/kegg/database> "KEGG Annotation Tool")
- [ ] AntiSMASH annotations [AntiSMASH](</path/to/AntiSMASH/github> "AntiSMASH")
- [ ] Antibiotic resistance mechanisms annotations [CARD database](<path/to/card/db> "CARD Database")

## Evaluation Datasets

- spike-in of known genomes to soil sample
- spike-in of MIX-51 to soil sample
